LOADING DATASET 
CONVERTING INTO DATAFRAME
AND VERIFYING IT

In [1]:
import pandas as pd

In [2]:
data= pd.read_csv("Data//Foodpanda Analysis Dataset - Foodpanda Analysis Dataset.csv")

In [3]:
data

,customer_id,gender,age,city,signup_date,order_id,order_date,restaurant_name,dish_name,category,quantity,price,payment_method,order_frequency,last_order_date,loyalty_points,churned,rating,rating_date,delivery_status
0,C5663,Male,Adult,Peshawar,1/14/2024,O9663,8/23/2023,McDonald's,Burger,Italian,5,1478.27,Cash,38,7/19/2025,238,Active,NaN,10/14/2024,Cancelled
1,C2831,Male,Adult,Multan,7/7/2024,O6831,8/23/2023,KFC,Burger,Italian,3,956.04,Wallet,24,11/25/2024,81,Active,2.0,8/21/2025,Delayed
2,C2851,Other,Senior,Multan,6/20/2025,O6851,8/23/2023,Pizza Hut,Fries,Italian,2,882.51,Cash,42,5/10/2025,82,Inactive,3.0,9/19/2024,Delayed
3,C1694,Female,Senior,Peshawar,9/5/2023,O5694,8/23/2023,Subway,Pizza,Dessert,4,231.30,Card,27,7/24/2025,45,Inactive,2.0,6/29/2025,Delayed
4,C4339,Other,Senior,Lahore,12/29/2023,O8339,8/24/2023,KFC,Sandwich,Dessert,1,1156.69,Cash,35,12/21/2024,418,Inactive,NaN,3/6/2025,Cancelled
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5995,C6849,Male,Adult,Multan,11/25/2024,O10849,8/22/2025,Pizza Hut,Burger,Italian,4,875.71,Cash,28,11/29/2024,166,Active,NaN,12/30/2024,Cancelled
5996,C3787,Female,Adult,Islamabad,1/28/2025,O7787,8/22/2025,KFC,Pizza,Italian,5,1118.26,Cash,12,6/8/2025,193,Inactive,3.0,2/9/2025,Delayed
5997,C2841,Other,Teenager,Islamabad,10/19/2023,O6841,8/22/2025,KFC,Sandwich,Italian,4,1005.83,Card,31,12/30/2024,278,Active,NaN,3/23/2025,Cancelled
5998,C1624,Male,Adult,Islamabad,6/17/2024,O5624,8/22/2025,KFC,Fries,Fast Food,4,1226.10,Card,37,12/27/2024,55,Inactive,2.0,3/15/2025,Delivered
5999,C2068,Female,Adult,Multan,3/15/2025,O6068,8/22/2025,Burger King,Fries,Fast Food,3,1131.27,Card,2,6/13/2025,41,Inactive,1.0,7/15/2025,Delayed

In [4]:
df_data=pd.DataFrame(data)

In [5]:
df_data

,customer_id,gender,age,city,signup_date,order_id,order_date,restaurant_name,dish_name,category,quantity,price,payment_method,order_frequency,last_order_date,loyalty_points,churned,rating,rating_date,delivery_status
0,C5663,Male,Adult,Peshawar,1/14/2024,O9663,8/23/2023,McDonald's,Burger,Italian,5,1478.27,Cash,38,7/19/2025,238,Active,NaN,10/14/2024,Cancelled
1,C2831,Male,Adult,Multan,7/7/2024,O6831,8/23/2023,KFC,Burger,Italian,3,956.04,Wallet,24,11/25/2024,81,Active,2.0,8/21/2025,Delayed
2,C2851,Other,Senior,Multan,6/20/2025,O6851,8/23/2023,Pizza Hut,Fries,Italian,2,882.51,Cash,42,5/10/2025,82,Inactive,3.0,9/19/2024,Delayed
3,C1694,Female,Senior,Peshawar,9/5/2023,O5694,8/23/2023,Subway,Pizza,Dessert,4,231.30,Card,27,7/24/2025,45,Inactive,2.0,6/29/2025,Delayed
4,C4339,Other,Senior,Lahore,12/29/2023,O8339,8/24/2023,KFC,Sandwich,Dessert,1,1156.69,Cash,35,12/21/2024,418,Inactive,NaN,3/6/2025,Cancelled
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5995,C6849,Male,Adult,Multan,11/25/2024,O10849,8/22/2025,Pizza Hut,Burger,Italian,4,875.71,Cash,28,11/29/2024,166,Active,NaN,12/30/2024,Cancelled
5996,C3787,Female,Adult,Islamabad,1/28/2025,O7787,8/22/2025,KFC,Pizza,Italian,5,1118.26,Cash,12,6/8/2025,193,Inactive,3.0,2/9/2025,Delayed
5997,C2841,Other,Teenager,Islamabad,10/19/2023,O6841,8/22/2025,KFC,Sandwich,Italian,4,1005.83,Card,31,12/30/2024,278,Active,NaN,3/23/2025,Cancelled
5998,C1624,Male,Adult,Islamabad,6/17/2024,O5624,8/22/2025,KFC,Fries,Fast Food,4,1226.10,Card,37,12/27/2024,55,Inactive,2.0,3/15/2025,Delivered
5999,C2068,Female,Adult,Multan,3/15/2025,O6068,8/22/2025,Burger King,Fries,Fast Food,3,1131.27,Card,2,6/13/2025,41,Inactive,1.0,7/15/2025,Delayed

In [6]:
type(data)

pandas.core.frame.DataFrame

In [7]:
type(df_data)

pandas.core.frame.DataFrame

EXPLORATORY DATA ANALYSIS

In [8]:
df_data.shape

(6000, 20)

Difference between .info (without parentheses) and .info( with parentheses)

This refers to the method itself, it does not execute it.

You get a method object, not the information you want.

.info() (with parentheses)

This calls the method, actually runs it, and prints the summary.

In [31]:
data.info

<bound method DataFrame.info of      customer_id  gender       age       city signup_date order_id order_date  \
0          C5663    Male     Adult   Peshawar   1/14/2024    O9663  8/23/2023
1          C2831    Male     Adult     Multan    7/7/2024    O6831  8/23/2023
2          C2851   Other    Senior     Multan   6/20/2025    O6851  8/23/2023
3          C1694  Female    Senior   Peshawar    9/5/2023    O5694  8/23/2023
4          C4339   Other    Senior     Lahore  12/29/2023    O8339  8/24/2023
...          ...     ...       ...        ...         ...      ...        ...
5995       C6849    Male     Adult     Multan  11/25/2024   O10849  8/22/2025
5996       C3787  Female     Adult  Islamabad   1/28/2025    O7787  8/22/2025
5997       C2841   Other  Teenager  Islamabad  10/19/2023    O6841  8/22/2025
5998       C1624    Male     Adult  Islamabad   6/17/2024    O5624  8/22/2025
5999       C2068  Female     Adult     Multan   3/15/2025    O6068  8/22/2025

     restaurant_name dish_name   category  quantity    price payment_method  \
0         McDonald's    Burger    Italian         5  1478.27           Cash
1                KFC    Burger    Italian         3   956.04         Wallet
2          Pizza Hut     Fries    Italian         2   882.51           Cash
3             Subway     Pizza    Dessert         4   231.30           Card
4                KFC  Sandwich    Dessert         1  1156.69           Cash
...              ...       ...        ...       ...      ...            ...
5995       Pizza Hut    Burger    Italian         4   875.71           Cash
5996             KFC     Pizza    Italian         5  1118.26           Cash
5997             KFC  Sandwich    Italian         4  1005.83           Card
5998             KFC     Fries  Fast Food         4  1226.10           Card
5999     Burger King     Fries  Fast Food         3  1131.27           Card

      order_frequency last_order_date  loyalty_points   churned  rating  \
0                  38       7/19/2025             238    Active     NaN
1                  24      11/25/2024              81    Active     2.0
2                  42       5/10/2025              82  Inactive     3.0
3                  27       7/24/2025              45  Inactive     2.0
4                  35      12/21/2024             418  Inactive     NaN
...               ...             ...             ...       ...     ...
5995               28      11/29/2024             166    Active     NaN
5996               12        6/8/2025             193  Inactive     3.0
5997               31      12/30/2024             278    Active     NaN
5998               37      12/27/2024              55  Inactive     2.0
5999                2       6/13/2025              41  Inactive     1.0

     rating_date delivery_status
0     10/14/2024       Cancelled
1      8/21/2025         Delayed
2      9/19/2024         Delayed
3      6/29/2025         Delayed
4       3/6/2025       Cancelled
...          ...             ...
5995  12/30/2024       Cancelled
5996    2/9/2025         Delayed
5997   3/23/2025       Cancelled
5998   3/15/2025       Delivered
5999   7/15/2025         Delayed

[6000 rows x 20 columns]>

In [32]:
data.describe

<bound method NDFrame.describe of      customer_id  gender       age       city signup_date order_id order_date  \
0          C5663    Male     Adult   Peshawar   1/14/2024    O9663  8/23/2023
1          C2831    Male     Adult     Multan    7/7/2024    O6831  8/23/2023
2          C2851   Other    Senior     Multan   6/20/2025    O6851  8/23/2023
3          C1694  Female    Senior   Peshawar    9/5/2023    O5694  8/23/2023
4          C4339   Other    Senior     Lahore  12/29/2023    O8339  8/24/2023
...          ...     ...       ...        ...         ...      ...        ...
5995       C6849    Male     Adult     Multan  11/25/2024   O10849  8/22/2025
5996       C3787  Female     Adult  Islamabad   1/28/2025    O7787  8/22/2025
5997       C2841   Other  Teenager  Islamabad  10/19/2023    O6841  8/22/2025
5998       C1624    Male     Adult  Islamabad   6/17/2024    O5624  8/22/2025
5999       C2068  Female     Adult     Multan   3/15/2025    O6068  8/22/2025

     restaurant_name dish_name   category  quantity    price payment_method  \
0         McDonald's    Burger    Italian         5  1478.27           Cash
1                KFC    Burger    Italian         3   956.04         Wallet
2          Pizza Hut     Fries    Italian         2   882.51           Cash
3             Subway     Pizza    Dessert         4   231.30           Card
4                KFC  Sandwich    Dessert         1  1156.69           Cash
...              ...       ...        ...       ...      ...            ...
5995       Pizza Hut    Burger    Italian         4   875.71           Cash
5996             KFC     Pizza    Italian         5  1118.26           Cash
5997             KFC  Sandwich    Italian         4  1005.83           Card
5998             KFC     Fries  Fast Food         4  1226.10           Card
5999     Burger King     Fries  Fast Food         3  1131.27           Card

      order_frequency last_order_date  loyalty_points   churned  rating  \
0                  38       7/19/2025             238    Active     NaN
1                  24      11/25/2024              81    Active     2.0
2                  42       5/10/2025              82  Inactive     3.0
3                  27       7/24/2025              45  Inactive     2.0
4                  35      12/21/2024             418  Inactive     NaN
...               ...             ...             ...       ...     ...
5995               28      11/29/2024             166    Active     NaN
5996               12        6/8/2025             193  Inactive     3.0
5997               31      12/30/2024             278    Active     NaN
5998               37      12/27/2024              55  Inactive     2.0
5999                2       6/13/2025              41  Inactive     1.0

     rating_date delivery_status
0     10/14/2024       Cancelled
1      8/21/2025         Delayed
2      9/19/2024         Delayed
3      6/29/2025         Delayed
4       3/6/2025       Cancelled
...          ...             ...
5995  12/30/2024       Cancelled
5996    2/9/2025         Delayed
5997   3/23/2025       Cancelled
5998   3/15/2025       Delivered
5999   7/15/2025         Delayed

[6000 rows x 20 columns]>

In [33]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6000 entries, 0 to 5999
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   customer_id      6000 non-null   object
 1   gender           6000 non-null   object
 2   age              6000 non-null   object
 3   city             6000 non-null   object
 4   signup_date      6000 non-null   object
 5   order_id         6000 non-null   object
 6   order_date       6000 non-null   object
 7   restaurant_name  6000 non-null   object
 8   dish_name        6000 non-null   object
 9   category         6000 non-null   object
 10  quantity         6000 non-null   int64
 11  price            6000 non-null   float64
 12  payment_method   6000 non-null   object
 13  order_frequency  6000 non-null   int64
 14  last_order_date  6000 non-null   object
 15  loyalty_points   6000 non-null   int64
 16  churned          6000 non-null   object
 17  rating           4032 non-null   float64
 18  rating_date      6000 non-null   object
 19  delivery_status  6000 non-null   object
dtypes: float64(2), int64(3), object(15)
memory usage: 937.6+ KB

This shows that there are 20 columns and all have non-null values, whereas, rating column has 1968 missing values.

In [34]:
data.describe()

          quantity        price  order_frequency  loyalty_points       rating
count  6000.000000  6000.000000      6000.000000     6000.000000  4032.000000
mean      2.991667   800.524880        25.304667      250.173667     3.012153
std       1.414778   404.855029        14.358930      144.608478     1.411615
min       1.000000   100.300000         1.000000        0.000000     1.000000
25%       2.000000   441.997500        13.000000      125.000000     2.000000
50%       3.000000   806.460000        25.000000      249.500000     3.000000
75%       4.000000  1149.737500        37.000000      378.000000     4.000000
max       5.000000  1499.950000        50.000000      500.000000     5.000000

In [35]:
data.describe(include='all')

,customer_id,gender,age,city,signup_date,order_id,order_date,restaurant_name,dish_name,category,quantity,price,payment_method,order_frequency,last_order_date,loyalty_points,churned,rating,rating_date,delivery_status
count,6000,6000,6000,6000,6000,6000,6000,6000,6000,6000,6000.000000,6000.000000,6000,6000.000000,6000,6000.000000,6000,4032.000000,6000,6000
unique,6000,3,3,5,730,6000,730,5,5,5,NaN,NaN,3,NaN,366,NaN,2,NaN,366,3
top,C5663,Female,Teenager,Multan,10/18/2023,O9663,9/8/2024,Subway,Pasta,Italian,NaN,NaN,Cash,NaN,8/13/2025,NaN,Active,NaN,6/14/2025,Delivered
freq,1,2018,2062,1256,18,1,20,1260,1262,1236,NaN,NaN,2039,NaN,28,NaN,3016,NaN,27,2060
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.991667,800.524880,NaN,25.304667,NaN,250.173667,NaN,3.012153,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.414778,404.855029,NaN,14.358930,NaN,144.608478,NaN,1.411615,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,100.300000,NaN,1.000000,NaN,0.000000,NaN,1.000000,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.000000,441.997500,NaN,13.000000,NaN,125.000000,NaN,2.000000,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.000000,806.460000,NaN,25.000000,NaN,249.500000,NaN,3.000000,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.000000,1149.737500,NaN,37.000000,NaN,378.000000,NaN,4.000000,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.000000,1499.950000,NaN,50.000000,NaN,500.000000,NaN,5.000000,NaN,NaN

In [36]:
data.describe(include=['object'])

,customer_id,gender,age,city,signup_date,order_id,order_date,restaurant_name,dish_name,category,payment_method,last_order_date,churned,rating_date,delivery_status
count,6000,6000,6000,6000,6000,6000,6000,6000,6000,6000,6000,6000,6000,6000,6000
unique,6000,3,3,5,730,6000,730,5,5,5,3,366,2,366,3
top,C5663,Female,Teenager,Multan,10/18/2023,O9663,9/8/2024,Subway,Pasta,Italian,Cash,8/13/2025,Active,6/14/2025,Delivered
freq,1,2018,2062,1256,18,1,20,1260,1262,1236,2039,28,3016,27,2060

In [37]:
data['gender'].value_counts()

gender
Female    2018
Male      2017
Other     1965
Name: count, dtype: int64

In [38]:
data['age'].unique()

array(['Adult', 'Senior', 'Teenager'], dtype=object)

In [39]:
data['gender'].unique()

array(['Male', 'Other', 'Female'], dtype=object)

In [40]:
data['age'].value_counts()

age
Teenager    2062
Adult       1984
Senior      1954
Name: count, dtype: int64

In [41]:
data['city'].value_counts()

city
Multan       1256
Lahore       1217
Peshawar     1195
Islamabad    1187
Karachi      1145
Name: count, dtype: int64

In [42]:
data.groupby('churned')['gender'].value_counts()

churned   gender
Active    Female    1027
          Male      1009
          Other      980
Inactive  Male      1008
          Female     991
          Other      985
Name: count, dtype: int64

In [43]:
data.groupby('churned')['age'].value_counts()

churned   age
Active    Teenager    1046
          Adult       1021
          Senior       949
Inactive  Teenager    1016
          Senior      1005
          Adult        963
Name: count, dtype: int64

In [44]:
data.groupby('churned')['city'].value_counts()

churned   city
Active    Peshawar     623
          Multan       608
          Islamabad    602
          Karachi      597
          Lahore       586
Inactive  Multan       648
          Lahore       631
          Islamabad    585
          Peshawar     572
          Karachi      548
Name: count, dtype: int64

In [45]:
data.groupby('age')['gender'].value_counts()

age       gender
Adult     Male      675
          Female    667
          Other     642
Senior    Female    669
          Male      647
          Other     638
Teenager  Male      695
          Other     685
          Female    682
Name: count, dtype: int64

In [46]:
data.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
5995    False
5996    False
5997    False
5998    False
5999    False
Length: 6000, dtype: bool

In [47]:
data.groupby('churned')['delivery_status'].value_counts()

churned   delivery_status
Active    Delivered          1042
          Cancelled           996
          Delayed             978
Inactive  Delivered          1018
          Delayed             994
          Cancelled           972
Name: count, dtype: int64

In [48]:
data.groupby(['gender','age','delivery_status'])['churned'].value_counts()

gender  age       delivery_status  churned
Female  Adult     Cancelled        Active      117
                                   Inactive    103
                  Delayed          Active      134
                                   Inactive    109
                  Delivered        Inactive    105
                                   Active       99
        Senior    Cancelled        Inactive    109
                                   Active      103
                  Delayed          Inactive    119
                                   Active       91
                  Delivered        Active      126
                                   Inactive    121
        Teenager  Cancelled        Active      117
                                   Inactive    102
                  Delayed          Active      117
                                   Inactive    100
                  Delivered        Active      123
                                   Inactive    123
Male    Adult     Cancelled        Active      116
                                   Inactive     98
                  Delayed          Active      113
                                   Inactive    103
                  Delivered        Active      127
                                   Inactive    118
        Senior    Cancelled        Inactive    119
                                   Active       98
                  Delayed          Inactive    110
                                   Active      105
                  Delivered        Active      112
                                   Inactive    103
        Teenager  Cancelled        Inactive    111
                                   Active      109
                  Delayed          Inactive    130
                                   Active       99
                  Delivered        Active      130
                                   Inactive    116
Other   Adult     Cancelled        Inactive    117
                                   Active      105
                  Delayed          Active      111
                                   Inactive     96
                  Delivered        Inactive    114
                                   Active       99
        Senior    Cancelled        Active      110
                                   Inactive    107
                  Delayed          Inactive    110
                                   Active       93
                  Delivered        Active      111
                                   Inactive    107
        Teenager  Cancelled        Active      121
                                   Inactive    106
                  Delayed          Inactive    117
                                   Active      115
                  Delivered        Active      115
                                   Inactive    111
Name: count, dtype: int64

In [49]:
data.columns

Index(['customer_id', 'gender', 'age', 'city', 'signup_date', 'order_id',
       'order_date', 'restaurant_name', 'dish_name', 'category', 'quantity',
       'price', 'payment_method', 'order_frequency', 'last_order_date',
       'loyalty_points', 'churned', 'rating', 'rating_date',
       'delivery_status'],
      dtype='object')

In [50]:
for col in data.columns:
    print(f"{col}: {data[col].nunique()} unique values")

customer_id: 6000 unique values
gender: 3 unique values
age: 3 unique values
city: 5 unique values
signup_date: 730 unique values
order_id: 6000 unique values
order_date: 730 unique values
restaurant_name: 5 unique values
dish_name: 5 unique values
category: 5 unique values
quantity: 5 unique values
price: 5872 unique values
payment_method: 3 unique values
order_frequency: 50 unique values
last_order_date: 366 unique values
loyalty_points: 501 unique values
churned: 2 unique values
rating: 5 unique values
rating_date: 366 unique values
delivery_status: 3 unique values

In [51]:
import matplotlib.pyplot as plt

In [52]:
import seaborn as sns

KeyError: 'Churned'